template = "https://github.com/giellalt/template-lang-und"
rev_id = 125
template_sha = "fdeb4951f8903c6226ba77833bbc3ad89191adfb"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
