template = "https://github.com/giellalt/template-lang-und"
rev_id = 154
template_sha = "42b3e17adab03a6d3de2a529e992f1c09cb4cf0f"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
