template = "https://github.com/giellalt/template-lang-und"
rev_id = 216
template_sha = "d7898cba241a813df1ca0cb537fa8cc273e1d838"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
