template = "https://github.com/giellalt/template-lang-und"
rev_id = 147
template_sha = "94ba09b9aec29cb7c92e29ab6d715415f99f825e"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
